### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by iosWellLin** [jkpang/PPNetworkHelper#1]
[self getData:YES url:@"http://www.qinto.com/wap/index.php?ctl=article_cate&act=api_app_getarticle_cate&num=1&p=1"];
你这个url是什么意思，无网络还要传url吗

**Comment by jkpang** [comment]
在无网络的时候根据传入的URL读取出对应的缓存数据,跟字典的存取Key-value的原理是一样的,不然数据的存取就乱套了.

**Comment by jkpang** [comment]
刚刚看了demo中[self getData:YES url:@"http://www.qinto.com/wap/index.php?ctl=article_cate&act=api_app_getarticle_cate&num=1&p=1"];传入的参数url应该为dataUrl,是我测试的时候忘记改过来了.@iosWellLin

**Comment by iosWellLin** [comment]
问个问题，我的request还有这么一段  [request addValue: @"b8931873de4129ff4e93e4022d5ad45b" forHTTPHeaderField: @"apikey"];
如果用你的方法应该怎么调

**Comment by jkpang** [comment]
@iosWellLin 噢,设置请求头的接口我没有暴露出来,你可以在PPNetworkHelper.m文件里的+ (AFHTTPSessionManager *)createAFHTTPSessionManager 中 方法中设置:[manager.requestSerializer setValue:@"b8931873de4129ff4e93e4022d5ad45b"  forHTTPHeaderField:@"apikey"];  我感觉请求头的全局设置一次就好了,再暴露出来一个方法的话就比较乱了.谢谢.

**Comment by iosWellLin** [comment]
可以了
