### ISSUE TITLE
关于上传文件

### ISSUE THREAD

**Issue by beiguancyc** [jkpang/PPNetworkHelper#12]
仔细看了您的代码。其中上传图片的方法uploadWithURL仅能用来上传图片无法上传其他文件，您说也可以上传其他文件，不知如何使用？

**Comment by jkpang** [comment]
不好意思哈,上次是我在群里面说错了的, 目前uploadWithURL暂时只能用来上传一张或多张图片,,以后有时间我会改进的 ,谢谢你的问题@beiguancyc

**Comment by beiguancyc** [comment]
非常感谢您的回复。也非常感谢您的代码。
