### ISSUE TITLE
上传图片fileName参数还是数组好些吧

### ISSUE THREAD

**Issue by diaoshihao** [jkpang/PPNetworkHelper#14]
上传多张图片时若需要自定义图片文件名如“zhangsan”、“lisi”就很不方便了，还是之前使用数组的方式好些，现在使用fileName1，fileName2。。。之前一直用的数组，刚更新了才发现的，现在我只好修改一下你的代码了😄

**Comment by jkpang** [comment]
非常感谢你的建议, 版本0.6.0已经将fileName参数改为了数组,并且默认值是已时间字符串命名 @diaoshihao
