### ISSUE TITLE
原理请教

### ISSUE THREAD

**Issue by hanjunqiang** [jkpang/PPNetworkHelper#15]
你好，请问缓存的数据，后台修改了某条数据的值，比如点赞数，那么二次刷新的时候怎么判断是否变化的呢？

**Comment by jkpang** [comment]
PPNetworkHelper在二次刷新的时候没有判断服务器数据是否变化,PPNetworkHelper的自动缓存是: 每成功请求一次服务器数据,,本地缓存就更新一次. @hanjunqiang

**Comment by hanjunqiang** [comment]
en，👌

**Comment by jcxc** [comment]
可否在success的block里判断网络返回数据是否与本地缓存数据一致，一致的话可不用再次缓存，不一致再缓存并返回数据刷新界面？

**Comment by hanjunqiang** [comment]
你想怎么判断请求的数据和缓存是否一致？

发自我的vivo智能手机

JcccZ <notifications@github.com>编写：
