### ISSUE TITLE
downloadWithURL时httphead设置无效

### ISSUE THREAD

**Issue by beiguancyc** [jkpang/PPNetworkHelper#17]
downloadWithURL方法调用时，[PPNetworkHelper setValue:@"123" forHTTPHeaderField:@"staffid"];设置的http头无效，上传的时候有效

**Comment by beiguancyc** [comment]
看了代码，发现下载时没法修改httphead。能否添加修改head的方法？目前自行修改代码添加

**Comment by jkpang** [comment]
[PPNetworkHelper setValue:@"123" forHTTPHeaderField:@"staffid"] 这样设置没有效果? 你现在是怎样添加的 @beiguancyc

**Comment by beiguancyc** [comment]
先调用[PPNetworkHelper setValue:@"123" forHTTPHeaderField:@"staffid"]，后调用downloadWithURL。下载时head没有添加staffid

**Comment by jkpang** [comment]
你自行修改的代码是怎样写的?在下载的时候可以成功设置请求头吗? @beiguancyc

**Comment by beiguancyc** [comment]
修改downloadWithURL方法，增加NSDictionary类型的参数head，方法内的request改为NSMutableURLRequest类型，然后如下即可
for (NSString *key in head) {
        [request setValue:head[key] forHTTPHeaderField:key];
    }

**Comment by jkpang** [comment]
下载方法使用[PPNetworkHelper setValue:@"123" forHTTPHeaderField:@"staffid"]设置不了请求头,原因可能是downloadWithURL中的NSURLRequest的对象是我自己创建的,不受AFHTTPRequestSerializer对象的控制,所以设置不了,,需要你手动设置NSURLRequest的请求头才起效.        看来目前只能由你修改源码手动设置了,非常感谢你的提问! @beiguancyc
