### ISSUE TITLE
请问一下用缓存会走2次方法怎么处理呢？

### ISSUE THREAD

**Issue by github410117** [jkpang/PPNetworkHelper#22]
例如我用来缓存cell数据，使用有缓存的方法进行数据请求，框架会先走缓存方法，然后再去走正常网络请求，但是这样造成了会2次刷新tableview，请教一下这个有啥好的处理办法吗？

**Comment by beiguancyc** [comment]
先加载缓存再从网络获取，必然刷新两次啊！

**Comment by github410117** [comment]
因为我有个地方需要获取数据后然后push，这样的话，就会push 2次！

**Comment by jkpang** [comment]
你的这个这个地方一定要有缓存的这个需求吗? 如果此地方缓存是非必须的,,可以用无缓存的请求方法 @ @github410117
