### ISSUE TITLE
建议在请求成功后，对结果加入加入统一处理回调

### ISSUE THREAD

**Issue by 1617176084** [jkpang/PPNetworkHelper#23]
>1有些对于token 失效  或者其他 业务需求需要对所有请求的code返回码进行处理

**Comment by jkpang** [comment]
每家公司后台数据字段定义不尽相同, 无法统一处理. 这个需要对应自己公司的需求来做处理,以不变应万变

**Comment by 1617176084** [comment]
@jkpang 是我没说清楚，具体描述为是一个可配置的回调block ，如PPHttpRequestSuccessAll，用户只要在唯一一个地方处理就可以了，这样会方便很多需要统一处理信息的事情，如果还没听明白我可以再说一次。


/** 请求成功并统一处理的Block */
typedef void(^PPHttpRequestSuccessAll)(id responseObject);

**Comment by 1617176084** [comment]
另外一个Issues你也要注意下，URL传入的未经过编码字符则会崩溃，这种情况产生在含有空格，中文，特殊符号等字符串，每个链接都需要处理又不现实，所以你需要考虑下是否统一处理下

**Comment by jkpang** [comment]
没必要这样吧,这个成功的block完全可以根据自己APP网络层的业务逻辑自定义.   对请求传入的URL处理自己完全可以封装一个公共方法,不需要自己每次调用,处理起来更加灵活,还是那个问题.. 每个公司的后台的编码格式可能会不一样,如果我在PPNetworkHelper中把URL统一处理成GBK或者其他格式,这样肯定会出问题..像我现在公司的后台,  在请求时都可以直接带中文字符. @1617176084

**Comment by 1617176084** [comment]
这些都应该是个配置项，用户不需要就没问题，需要的话就可以直接拿来用，重复造轮子这种事。。。。你懂得

**Comment by 1617176084** [comment]
PPNetworkHelper
不就是对AF的封装么？如果还要对PPNetworkHelper进行封装。。。我觉得这些都会使适用性做出折扣

**Comment by jkpang** [comment]
对啊,你说的没错. 重复造轮子怎么了,至少我是用自己写的东西自己用,用得光明正大,心安理得. 你有兴趣,你也可以自己造啊. 重复造轮子有错了? @1617176084

**Comment by 1617176084** [comment]
额 。。。

**Comment by 1617176084** [comment]
好吧  先谢谢了

**Comment by jkpang** [comment]
重复造轮子并不是坏事,只要是自己用心的写的就有存在的意义. 请你不要鄙视
