### ISSUE TITLE
希望可以使用cocoapods引入

### ISSUE THREAD

**Issue by hllGitHub** [jkpang/PPNetworkHelper#24]

**Comment by jkpang** [comment]
可以使用cocoapods导入的, pod 'PPNetworkHelper' @hllGitHub

**Comment by jkpang** [comment]
Installation 安装
 1.手动安装: 下载DEMO后,将子文件夹PPNetworkHelper拖入到项目中, 导入头文件PPNetworkHelper.h开始使用 
2.CocoaPods安装: first pod 'PPNetworkHelper',:git => 'https://github.com/jkpang/PPNetworkHelper.git' 
then pod install或pod install --no-repo-update
如果发现pod search PPNetworkHelper 不是最新版本，在终端执行pod setup命令更新本地spec镜像缓存(时间可能有点长),重新搜索就OK了

**Comment by hllGitHub** [comment]
是的，确实有。不过##Installation 安装 ###1.手动安装: 下载DEMO后,将子文件夹PPNetworkHelper拖入到项目中, 导入头文件PPNetworkHelper.h开始使用 ###2.CocoaPods安装: first pod 'PPNetworkHelper',:git => 'https://github.com/jkpang/PPNetworkHelper.git' then pod install或pod install --no-repo-update 这样写都混在一起了，请问下可以把readme.md部分重新排版一下吗？有点乱 ##跟文字之间留空就能出标题了。

**Comment by jkpang** [comment]
可能是上个星期GitHub做出了调整,导致显示混论,,抽时间我会重新排版

**Comment by hllGitHub** [comment]
重新排版下大家方便看，，现在的确实有点混乱 ##不应该出现
