### ISSUE TITLE
可以设置baseUrl吗？项目里用到的通常都会有baseUrl，不仅方便也可以随时切换服务器

### ISSUE THREAD

**Issue by hllGitHub** [jkpang/PPNetworkHelper#25]

**Comment by jkpang** [comment]
现在暂时还没有开放设置baseUrl的接口, 我这边的写法是把服务器域名定义成对应的常量字符串,然后利用宏定义来判断不同的生产环境,如下图所示:.下个版本会把AFHTTPSessionManager的对象开放出来,方便开发者对网络请求的各种设置.
![image](https://cloud.githubusercontent.com/assets/17583451/24487470/4c862324-1542-11e7-9b2c-606779088850.png)

**Comment by hllGitHub** [comment]
我们的项目有点特殊，非线上版本都有个功能可以自行在app里切换测试环境以及正式环境。不能设置为宏，目前是采用跟你类似的方式，拼接的。
