### ISSUE TITLE
无法设置请求头

### ISSUE THREAD

**Issue by iOSwxh** [jkpang/PPNetworkHelper#26]
[PPNetworkHelper setValue: forHTTPHeaderField:]不起作用

如果在af里 这样设置是可用的
AFHTTPRequestSerializer *requestSerializer =  [AFJSONRequestSerializer serializer];

    [requestSerializer setValue: forHTTPHeaderField:];
manager.requestSerializer = requestSerializer;

**Comment by jkpang** [comment]
[PPNetworkHelper setValue: forHTTPHeaderField:] 最终也是调用的 
[_sessionManager.requestSerializer setValue: forHTTPHeaderField:];

你有没有先设置[PPNetworkHelper setRequestSerializer:PPRequestSerializerJSON];
再调用[PPNetworkHelper setValue: forHTTPHeaderField:] 设置请求头呢 @iOSwxh
