### ISSUE TITLE
关于使用缓存问题

### ISSUE THREAD

**Issue by coderZhou10496** [jkpang/PPNetworkHelper#27]
第一次进入一个界面，先使用缓存，然后网络请求完成，再刷新界面。可当我对这个界面下拉刷新的时候，这时候不应该读取缓存吧，而是直接去网络请求，请求完成后再缓存数据，刷新界面。第二个需求，要调用无缓存接口，然后自己实现缓存功能？

**Comment by jkpang** [comment]
PPNetworkHelper默认的自动缓存策略是: 1.请求前先加载缓存(不管有无缓存)-->2.请求网络数据-->3.更新缓存. 如果这个缓存策略不符合你项目的设计,你可以使用无缓存请求+手动缓存的方式实现出适合自己项目的缓存策略 @coderZhou10496
