### ISSUE TITLE
与YYKit冲突

### ISSUE THREAD

**Issue by bsyqc163** [jkpang/PPNetworkHelper#32]
项目中通过CocoPods集成了YYKit，由于YYKit中已经包含了YYCache，而pod ‘PPnetworkHelper’会再次集成YYCache，导致冲突，怎么办

**Comment by jkpang** [comment]
那是因为YYKit中的YYCache没有使用pod分离, 所以pod判断不了重复的库,两种解决方法:
1. 不删除YYKit, 手动将PPNetworkHelper拖入到项目中;
2.删除YYKit, 将你需要YYKit中的组件以单个repo的形式导入到项目中,例如 : pod 'YYText' , pod 'YYModel' ..... @bsyqc163
