### ISSUE TITLE
在block里进行数据请求貌似会造成内存泄露

### ISSUE THREAD

**Issue by GoogGoodStudy** [jkpang/PPNetworkHelper#5]
![image](https://cloud.githubusercontent.com/assets/16487329/18663837/c1b72b2e-7f52-11e6-8c39-64b1e9985da9.png)
这样写貌似会造成循环引用。感谢大神的库，很好用。

**Comment by jkpang** [comment]
在你的那两个block里面使用PPNetworkHelper请求数据是不会产生内存泄露的，因为他们没有相互引用，你可以放心使用。 如果你这段代码有发生了内存泄露，可以加我QQ帮你看看😀

AndyPang

**Comment by GoogGoodStudy** [comment]
好的。我再看看
