### ISSUE TITLE
请教一个问题，只看到了存网络数据，这个存下来的网络数据在哪里用呢

### ISSUE THREAD

**Issue by songxing10000** [jkpang/PPNetworkHelper#7]
get如果带缓存了，下次再调用get就不应该访问网络，直接走缓存数据啊，
不知道是我没看懂代码，还是理解错了，求指教

**Comment by jkpang** [comment]
如果缓存的接口数据在服务器端有更新呢,如果不重新请求,岂不是一直都加载缓存的旧数据了?
PPNetworkHelper的缓存策略是,不管有无网络,都:

1.先加载上次缓存在本地的数据 ->展示
2.然后再请求服务器的数据 ->展示
3.最后再缓存本次的服务器数据 ->等待下次展示

所以当用户即使在没网络的情况下请求服务器数据失败,仍然可以加载上次缓存的数据,不会导致APP的界面一片空白,这样会极大的提升用户体验.   在某些情况下可以缓存一些常用且不会经常变动的数据,避免每次用到都要请求服务器,以减轻服务器的压力.
@songxing10000

**Comment by songxing10000** [comment]
如果缓存的接口数据在服务器端有更新呢,如果不重新请求,岂不是一直都加载缓存的旧数据了?
之前我也是这样想的，可是后台，在请求接口时，没有返回304给我，每次都是200。所以对于 缓存的处理比较头痛，

**Comment by jkpang** [comment]
那你用PPNetworkHelper就可以满足你的要求了,如果你非得要根据服务器给你返回的状态码来判断是否进行缓存,,那就要自己和后端工程师商量了,让他给你一个准确的状态码.

**Comment by songxing10000** [comment]
不错，明白了，感谢
