### ISSUE TITLE
新增加的一次性判断网络方法无效果。。。。。。

### ISSUE THREAD

**Issue by HZRZCW** [jkpang/PPNetworkHelper#9]
新增加的一次性判断网络方法无效果。。。。。。

**Comment by jkpang** [comment]
已经修复好了,你再试试看 @HZRZCW

**Comment by HZRZCW** [comment]
给力

**Comment by HZRZCW** [comment]
不好意思，我又试了下，还是不行。。。。。。

#pragma mark - 一次性网络状态判断
- (void)currentNetworkStatus
{
    if (kIsNetwork) {
        NSLog(@"有网络");
        if (kIsWWANNetwork) {
            NSLog(@"手机网络");
        }else if (kIsWiFiNetwork){
            NSLog(@"WiFi网络");
        }
    }
    // 或
//    if ([PPNetworkHelper isNetwork]) {
//        NSLog(@"有网络");
//        if ([PPNetworkHelper isWWANNetwork]) {
//            NSLog(@"手机网络");
//        }else if ([PPNetworkHelper isWiFiNetwork]){
//            NSLog(@"WiFi网络");
//        }
//    }
}
根本没打印

**Comment by jkpang** [comment]
你使用的是Xcode8+真机+iOS 10测试的吗? iOS10开始用真机会屏蔽掉NSLog的打印, 可以用printf替换 @HZRZCW

**Comment by HZRZCW** [comment]
@jkpang 这个没关系吧，没打印是因为kIsNetwork这个方法在明明有网络的情况下返回0，真机和模拟器都一样

**Comment by jkpang** [comment]
我这边测试时正常的,无网络,手机网络,WIFI网络都能检测出来,你用PPNetworkHelper demo试试看 ?@HZRZCW

**Comment by HZRZCW** [comment]
@jkpang #pragma mark - 一次性网络状态判断
- (void)currentNetworkStatus
{
    if (kIsNetwork) {
        printf("有网络");
        if (kIsWWANNetwork) {
            printf("手机网络");
        }else if (kIsWiFiNetwork){
            printf("WiFi网络");
        }
    }
    // 或
//    if ([PPNetworkHelper isNetwork]) {
//        NSLog(@"有网络");
//        if ([PPNetworkHelper isWWANNetwork]) {
//            NSLog(@"手机网络");
//        }else if ([PPNetworkHelper isWiFiNetwork]){
//            NSLog(@"WiFi网络");
//        }
//    }
}
是这个方法没执行，

 //实时监测网络状态
    [PPNetworkHelper networkStatusWithBlock:^(PPNetworkStatus networkStatus) {
        
        switch (networkStatus) {
            case PPNetworkStatusUnknown:
            case PPNetworkStatusNotReachable: {
                self.networkData.text = @"没有网络";
                
                [self getData:YES url:dataUrl];
                
                NSLog(@"无网络,加载缓存数据");
                break;
            }
            case PPNetworkStatusReachableViaWWAN:
            case PPNetworkStatusReachableViaWiFi: {
                [self getData:[[NSUserDefaults standardUserDefaults] boolForKey:@"isOn"] url:dataUrl];
                NSLog(@"有网络,请求网络数据");
                break;
            }
        }

    }];
这个方法还是有效果的，好奇怪

**Comment by jkpang** [comment]
你可以自行设置一个按钮响应, 把网络一次性判断方法放进去,每点击一次就切换一下网络状态,看打印出来的是不是对的 @HZRZCW

**Comment by HZRZCW** [comment]
@jkpang 这样做真的可以了，谢谢

**Comment by jkpang** [comment]
好的!希望你用的愉快! @HZRZCW
